### ISSUE TITLE
Automate testing of both IDE & Kai Client in a Windows environment with a non-admin user

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai-ci#10]
This task is focused on capturing the work needed to automate the testing of what we believe is our most difficult end user environment, a Windows non-admin user with limited privileges running in a corporate environment.

Related to https://github.com/konveyor/kai/issues/330

The below tasks are assumed to all be executed against a Windows Desktop provisioned in AWS.
See: https://aws.amazon.com/workspaces-family/workspaces/

Further assumption, the work done to automate and test the below is expected to reside in a GitHub repository under the Konveyor organization so the community may help use/enhance this automation code.

```[tasklist]
### Tasks
- [ ] https://github.com/konveyor/kai/issues/339
- [ ] https://github.com/konveyor/kai/issues/340
- [ ] https://github.com/konveyor/kai/issues/341
- [ ] https://github.com/konveyor/kai-ci/issues/14
- [ ] https://github.com/konveyor/kai-ci/issues/12
- [ ] https://github.com/konveyor/kai-ci/issues/11
- [ ] https://github.com/konveyor/kai-ci/issues/9
- [ ] https://github.com/konveyor/kai/issues/346
```
